package Main;

import Main.Componentes.Capacitor;
import Main.Componentes.Indutor;
import Main.Componentes.Resistor;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Principal extends javax.swing.JFrame {
    //exemplo
    ArrayList<Departamento> ListaDep;
    String modoDep;
    
    //trabalho
    ArrayList<Capacitor> ListaCapacitores;
    ArrayList<Indutor> ListaIndutores;
    ArrayList<Resistor> ListaResistores;
    
    public void carregarTabelaCapacitores(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Id","Tipo","Capacitância","Descrição","Quantidade"},0);

        for(int i=0;i<ListaCapacitores.size();i++){
            Object linha[] = new Object[]{ListaCapacitores.get(i).getId(),
                                          ListaCapacitores.get(i).getTipoCapacitor(),
                                          ListaCapacitores.get(i).getCapacitancia(),
                                          ListaCapacitores.get(i).getDescricao(),
                                          ListaCapacitores.get(i).getQuantidade()};
            modelo.addRow(linha);
        }
        
        tbl_dep_dpts.setModel(modelo);
        //tbl_dep_dpts.getColumnModel().getColumn(0).setPreferredWidth(50);
        //tbl_dep_dpts.getColumnModel().getColumn(1).setPreferredWidth(200);
    }
   
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setTitle("POO ROTH");
        setLocationRelativeTo(null);
        ListaDep = new ArrayList();
        
        ListaCapacitores = new ArrayList();
        ListaIndutores = new ArrayList();
        ListaResistores = new ArrayList();
        
        modoDep = "Navegar";
        ManipulaInterfaceCrudCapacitor();
    }
    
    public void ManipulaInterfaceCrudCapacitor(){
        switch(modoDep){
            case "Navegar":
                btnSalvarCapacitor.setEnabled(false);
                btnCancelarCapacitor.setEnabled(false);
                campoIdCapacitor.setEnabled(false);
                campoDescricaoCapacitor.setEnabled(false);
                campoQuantidadeCapacitor.setEnabled(false);
                btnNovoCapacitor.setEnabled(true);
                btnEditarCapacitor.setEnabled(false);
                btnExcluirCapacitor.setEnabled(false);
                break;
            
            case "Novo":
                btnSalvarCapacitor.setEnabled(true);
                btnCancelarCapacitor.setEnabled(true);
                campoIdCapacitor.setEnabled(true);
                campoDescricaoCapacitor.setEnabled(true);
                campoQuantidadeCapacitor.setEnabled(true);
                btnNovoCapacitor.setEnabled(false);
                btnEditarCapacitor.setEnabled(false);
                btnExcluirCapacitor.setEnabled(false);
                break;
                
            case "Editar":
                btnSalvarCapacitor.setEnabled(true);
                btnCancelarCapacitor.setEnabled(true);
                campoIdCapacitor.setEnabled(true);
                campoDescricaoCapacitor.setEnabled(true);
                btnNovoCapacitor.setEnabled(true);
                btnEditarCapacitor.setEnabled(false);
                btnExcluirCapacitor.setEnabled(false);
                break;
                
            case "Excluir":
                btnSalvarCapacitor.setEnabled(false);
                btnCancelarCapacitor.setEnabled(false);
                campoIdCapacitor.setEnabled(false);
                campoDescricaoCapacitor.setEnabled(false);
                campoQuantidadeCapacitor.setEnabled(false);
                btnNovoCapacitor.setEnabled(true);
                btnEditarCapacitor.setEnabled(false);
                btnExcluirCapacitor.setEnabled(false);
                break;
                
            case "Selecao":
                btnSalvarCapacitor.setEnabled(false);
                btnCancelarCapacitor.setEnabled(false);
                campoIdCapacitor.setEnabled(false);
                campoDescricaoCapacitor.setEnabled(false);
                campoQuantidadeCapacitor.setEnabled(false);
                btnNovoCapacitor.setEnabled(true);
                btnEditarCapacitor.setEnabled(true);
                btnExcluirCapacitor.setEnabled(true);
                break;
            default: System.out.println("Modo inválido");
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        tabCapacitores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dep_dpts = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoIdCapacitor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoDescricaoCapacitor = new javax.swing.JTextField();
        btnSalvarCapacitor = new javax.swing.JButton();
        btnCancelarCapacitor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        campoQuantidadeCapacitor = new javax.swing.JTextField();
        campoCapacitancia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboTipoCapacitor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnNovoCapacitor = new javax.swing.JButton();
        btnEditarCapacitor = new javax.swing.JButton();
        btnExcluirCapacitor = new javax.swing.JButton();
        botaoPesquisarNaInternet = new javax.swing.JButton();
        tabIndutores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_dep_dpts1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        campoId1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoDescricao1 = new javax.swing.JTextField();
        btn_capacitor_salvar1 = new javax.swing.JButton();
        btn_dep_cancelar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        campoQuantidade1 = new javax.swing.JTextField();
        campoCapacidade1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboTipoCapacitancia1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnNovoCapacitor1 = new javax.swing.JButton();
        btnEditarCapacitor1 = new javax.swing.JButton();
        btn_dep_excluir1 = new javax.swing.JButton();
        tabResistores = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_dep_dpts2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        campoId2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoDescricao2 = new javax.swing.JTextField();
        btn_capacitor_salvar2 = new javax.swing.JButton();
        btn_dep_cancelar2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        campoQuantidade2 = new javax.swing.JTextField();
        campoCapacidade2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        comboTipoCapacitancia2 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        btnNovoCapacitor2 = new javax.swing.JButton();
        btnEditarCapacitor2 = new javax.swing.JButton();
        btn_dep_excluir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabs.setToolTipText("");
        tabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbl_dep_dpts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo", "Capacitância", "Descrição", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_dep_dpts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dep_dptsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_dep_dpts);
        if (tbl_dep_dpts.getColumnModel().getColumnCount() > 0) {
            tbl_dep_dpts.getColumnModel().getColumn(0).setResizable(false);
            tbl_dep_dpts.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl_dep_dpts.getColumnModel().getColumn(1).setResizable(false);
            tbl_dep_dpts.getColumnModel().getColumn(2).setResizable(false);
            tbl_dep_dpts.getColumnModel().getColumn(3).setResizable(false);
            tbl_dep_dpts.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações"));

        jLabel1.setText("Id:");

        jLabel2.setText("Descrição:");

        campoDescricaoCapacitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDescricaoCapacitorActionPerformed(evt);
            }
        });

        btnSalvarCapacitor.setText("Salvar");
        btnSalvarCapacitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCapacitorActionPerformed(evt);
            }
        });

        btnCancelarCapacitor.setText("Cancelar");
        btnCancelarCapacitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCapacitorActionPerformed(evt);
            }
        });

        jLabel6.setText("Qtd:");

        campoQuantidadeCapacitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoQuantidadeCapacitorActionPerformed(evt);
            }
        });

        jLabel8.setText("Capacitância:");

        comboTipoCapacitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Eletrolítico", "Poliéster", "Cerâmico", "Tântalo" }));
        comboTipoCapacitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoCapacitorActionPerformed(evt);
            }
        });

        jLabel9.setText("Tipo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQuantidadeCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDescricaoCapacitor))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoIdCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTipoCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCapacitancia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnSalvarCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(campoIdCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(comboTipoCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(campoCapacitancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(campoQuantidadeCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(campoDescricaoCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvarCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelarCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnNovoCapacitor.setText("Novo");
        btnNovoCapacitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCapacitorActionPerformed(evt);
            }
        });

        btnEditarCapacitor.setText("Editar");
        btnEditarCapacitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCapacitorActionPerformed(evt);
            }
        });

        btnExcluirCapacitor.setText("Excluir");
        btnExcluirCapacitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCapacitorActionPerformed(evt);
            }
        });

        botaoPesquisarNaInternet.setText("Pesquisar na Internet");
        botaoPesquisarNaInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarNaInternetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCapacitoresLayout = new javax.swing.GroupLayout(tabCapacitores);
        tabCapacitores.setLayout(tabCapacitoresLayout);
        tabCapacitoresLayout.setHorizontalGroup(
            tabCapacitoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCapacitoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCapacitoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabCapacitoresLayout.createSequentialGroup()
                        .addComponent(btnNovoCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditarCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirCapacitor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoPesquisarNaInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabCapacitoresLayout.setVerticalGroup(
            tabCapacitoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCapacitoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tabCapacitoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEditarCapacitor, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnNovoCapacitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirCapacitor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoPesquisarNaInternet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Capacitores", tabCapacitores);

        tbl_dep_dpts1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo", "Capacitância", "Descrição", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_dep_dpts1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dep_dpts1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_dep_dpts1);
        if (tbl_dep_dpts1.getColumnModel().getColumnCount() > 0) {
            tbl_dep_dpts1.getColumnModel().getColumn(0).setResizable(false);
            tbl_dep_dpts1.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl_dep_dpts1.getColumnModel().getColumn(1).setResizable(false);
            tbl_dep_dpts1.getColumnModel().getColumn(2).setResizable(false);
            tbl_dep_dpts1.getColumnModel().getColumn(3).setResizable(false);
            tbl_dep_dpts1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações"));

        jLabel3.setText("Id:");

        jLabel4.setText("Descrição:");

        campoDescricao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDescricao1ActionPerformed(evt);
            }
        });

        btn_capacitor_salvar1.setText("Salvar");
        btn_capacitor_salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capacitor_salvar1ActionPerformed(evt);
            }
        });

        btn_dep_cancelar1.setText("Cancelar");
        btn_dep_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dep_cancelar1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Qtd:");

        campoQuantidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoQuantidade1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Capacitância:");

        comboTipoCapacitancia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Eletrolítico", "Poliéster", "Cerâmico", "Tântalo" }));
        comboTipoCapacitancia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoCapacitancia1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Tipo:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDescricao1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoId1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTipoCapacitancia1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCapacidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_capacitor_salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dep_cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(campoId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(comboTipoCapacitancia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(campoCapacidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(campoQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(campoDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_capacitor_salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_dep_cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNovoCapacitor1.setText("Novo");
        btnNovoCapacitor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCapacitor1ActionPerformed(evt);
            }
        });

        btnEditarCapacitor1.setText("Editar");
        btnEditarCapacitor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCapacitor1ActionPerformed(evt);
            }
        });

        btn_dep_excluir1.setText("Excluir");
        btn_dep_excluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dep_excluir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabIndutoresLayout = new javax.swing.GroupLayout(tabIndutores);
        tabIndutores.setLayout(tabIndutoresLayout);
        tabIndutoresLayout.setHorizontalGroup(
            tabIndutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabIndutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabIndutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabIndutoresLayout.createSequentialGroup()
                        .addComponent(btnNovoCapacitor1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarCapacitor1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_dep_excluir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabIndutoresLayout.setVerticalGroup(
            tabIndutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabIndutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabIndutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoCapacitor1)
                    .addComponent(btnEditarCapacitor1)
                    .addComponent(btn_dep_excluir1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Indutores", tabIndutores);

        tbl_dep_dpts2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo", "Capacitância", "Descrição", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_dep_dpts2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dep_dpts2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_dep_dpts2);
        if (tbl_dep_dpts2.getColumnModel().getColumnCount() > 0) {
            tbl_dep_dpts2.getColumnModel().getColumn(0).setResizable(false);
            tbl_dep_dpts2.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl_dep_dpts2.getColumnModel().getColumn(1).setResizable(false);
            tbl_dep_dpts2.getColumnModel().getColumn(2).setResizable(false);
            tbl_dep_dpts2.getColumnModel().getColumn(3).setResizable(false);
            tbl_dep_dpts2.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações"));

        jLabel5.setText("Id:");

        jLabel12.setText("Descrição:");

        campoDescricao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDescricao2ActionPerformed(evt);
            }
        });

        btn_capacitor_salvar2.setText("Salvar");
        btn_capacitor_salvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capacitor_salvar2ActionPerformed(evt);
            }
        });

        btn_dep_cancelar2.setText("Cancelar");
        btn_dep_cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dep_cancelar2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Qtd:");

        campoQuantidade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoQuantidade2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Capacitância:");

        comboTipoCapacitancia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Eletrolítico", "Poliéster", "Cerâmico", "Tântalo" }));
        comboTipoCapacitancia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoCapacitancia2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Tipo:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoQuantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDescricao2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoId2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTipoCapacitancia2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCapacidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_capacitor_salvar2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dep_cancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(campoId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(comboTipoCapacitancia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(campoCapacidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(campoQuantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(campoDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_capacitor_salvar2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_dep_cancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNovoCapacitor2.setText("Novo");
        btnNovoCapacitor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCapacitor2ActionPerformed(evt);
            }
        });

        btnEditarCapacitor2.setText("Editar");
        btnEditarCapacitor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCapacitor2ActionPerformed(evt);
            }
        });

        btn_dep_excluir2.setText("Excluir");
        btn_dep_excluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dep_excluir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabResistoresLayout = new javax.swing.GroupLayout(tabResistores);
        tabResistores.setLayout(tabResistoresLayout);
        tabResistoresLayout.setHorizontalGroup(
            tabResistoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabResistoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabResistoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabResistoresLayout.createSequentialGroup()
                        .addComponent(btnNovoCapacitor2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarCapacitor2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_dep_excluir2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabResistoresLayout.setVerticalGroup(
            tabResistoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabResistoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabResistoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoCapacitor2)
                    .addComponent(btnEditarCapacitor2)
                    .addComponent(btn_dep_excluir2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Resistores", tabResistores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs)
                .addContainerGap())
        );

        tabs.getAccessibleContext().setAccessibleName("Capacitores");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirCapacitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCapacitorActionPerformed
        int index = tbl_dep_dpts.getSelectedRow();
        if(index>=0 && index<ListaDep.size()){
            ListaDep.remove(index);
        }
        carregarTabelaCapacitores();
        modoDep = "Navegar";
        ManipulaInterfaceCrudCapacitor();
    }//GEN-LAST:event_btnExcluirCapacitorActionPerformed

    private void btnEditarCapacitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCapacitorActionPerformed
        modoDep = "Editar";
        ManipulaInterfaceCrudCapacitor();
    }//GEN-LAST:event_btnEditarCapacitorActionPerformed

    private void btnNovoCapacitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCapacitorActionPerformed
        campoIdCapacitor.setText("");
        campoDescricaoCapacitor.setText("");
        campoQuantidadeCapacitor.setText("");
        modoDep = "Novo";
        ManipulaInterfaceCrudCapacitor();
    }//GEN-LAST:event_btnNovoCapacitorActionPerformed

    private void comboTipoCapacitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoCapacitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoCapacitorActionPerformed

    private void campoQuantidadeCapacitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoQuantidadeCapacitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoQuantidadeCapacitorActionPerformed

    private void btnCancelarCapacitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCapacitorActionPerformed
        campoIdCapacitor.setText("");
        campoDescricaoCapacitor.setText("");
        campoQuantidadeCapacitor.setText("");
        modoDep = "Navegar";
        ManipulaInterfaceCrudCapacitor();
    }//GEN-LAST:event_btnCancelarCapacitorActionPerformed

    private void btnSalvarCapacitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCapacitorActionPerformed
        int id = Integer.parseInt(campoIdCapacitor.getText());
        String tipoCapacitancia = comboTipoCapacitor.getSelectedItem().toString();
        String descricao = campoDescricaoCapacitor.getText();
        float capacidade = Float.parseFloat(campoCapacitancia.getText());
        int qtd = Integer.parseInt(campoQuantidadeCapacitor.getText());

        if(modoDep.equals("Novo")){
            Capacitor c = new Capacitor(
                id,
                descricao,
                qtd,
                tipoCapacitancia,
                capacidade);
            ListaCapacitores.add(c);

            //Departamento D = new Departamento(cod, campoDescricaoCapacitor.getText());
            //ListaDep.add(D);
        }else if(modoDep.equals("Editar")){
            int index = tbl_dep_dpts.getSelectedRow();
            ListaDep.get(index).setCodigo(id);
            ListaDep.get(index).setNome(campoDescricaoCapacitor.getText());
        }

        carregarTabelaCapacitores();
        modoDep = "Navegar";
        ManipulaInterfaceCrudCapacitor();
        campoIdCapacitor.setText("");
        campoDescricaoCapacitor.setText("");
        campoQuantidadeCapacitor.setText("");
    }//GEN-LAST:event_btnSalvarCapacitorActionPerformed

    private void campoDescricaoCapacitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDescricaoCapacitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDescricaoCapacitorActionPerformed

    private void tbl_dep_dptsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dep_dptsMouseClicked
        int index = tbl_dep_dpts.getSelectedRow();
        if(index>=0 && index<ListaDep.size()){
            Departamento D = ListaDep.get(index);
            campoIdCapacitor.setText(String.valueOf(D.getCodigo()));
            campoDescricaoCapacitor.setText(D.getNome());
            modoDep = "Selecao";
            ManipulaInterfaceCrudCapacitor();
        }
    }//GEN-LAST:event_tbl_dep_dptsMouseClicked

    private void tbl_dep_dpts1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dep_dpts1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_dep_dpts1MouseClicked

    private void campoDescricao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDescricao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDescricao1ActionPerformed

    private void btn_capacitor_salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capacitor_salvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_capacitor_salvar1ActionPerformed

    private void btn_dep_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dep_cancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dep_cancelar1ActionPerformed

    private void campoQuantidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoQuantidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoQuantidade1ActionPerformed

    private void comboTipoCapacitancia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoCapacitancia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoCapacitancia1ActionPerformed

    private void btnNovoCapacitor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCapacitor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoCapacitor1ActionPerformed

    private void btnEditarCapacitor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCapacitor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarCapacitor1ActionPerformed

    private void btn_dep_excluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dep_excluir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dep_excluir1ActionPerformed

    private void tbl_dep_dpts2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dep_dpts2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_dep_dpts2MouseClicked

    private void campoDescricao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDescricao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDescricao2ActionPerformed

    private void btn_capacitor_salvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capacitor_salvar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_capacitor_salvar2ActionPerformed

    private void btn_dep_cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dep_cancelar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dep_cancelar2ActionPerformed

    private void campoQuantidade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoQuantidade2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoQuantidade2ActionPerformed

    private void comboTipoCapacitancia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoCapacitancia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoCapacitancia2ActionPerformed

    private void btnNovoCapacitor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCapacitor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoCapacitor2ActionPerformed

    private void btnEditarCapacitor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCapacitor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarCapacitor2ActionPerformed

    private void btn_dep_excluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dep_excluir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dep_excluir2ActionPerformed

    private void botaoPesquisarNaInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarNaInternetActionPerformed

        try{
            String textoSerBuscado =  JOptionPane.showInputDialog("Componente que deseja pesquisar nas interwebs: ");
            if ("".equals(textoSerBuscado)) throw new Exception();
            Desktop.getDesktop().browse(new URI("http://www.google.com.br/search?q="+textoSerBuscado));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,
                "Você não preenchou o campo de pesquisa, tente novamente.",
                "Ops!",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoPesquisarNaInternetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPesquisarNaInternet;
    private javax.swing.JButton btnCancelarCapacitor;
    private javax.swing.JButton btnEditarCapacitor;
    private javax.swing.JButton btnEditarCapacitor1;
    private javax.swing.JButton btnEditarCapacitor2;
    private javax.swing.JButton btnExcluirCapacitor;
    private javax.swing.JButton btnNovoCapacitor;
    private javax.swing.JButton btnNovoCapacitor1;
    private javax.swing.JButton btnNovoCapacitor2;
    private javax.swing.JButton btnSalvarCapacitor;
    private javax.swing.JButton btn_capacitor_salvar1;
    private javax.swing.JButton btn_capacitor_salvar2;
    private javax.swing.JButton btn_dep_cancelar1;
    private javax.swing.JButton btn_dep_cancelar2;
    private javax.swing.JButton btn_dep_excluir1;
    private javax.swing.JButton btn_dep_excluir2;
    private javax.swing.JTextField campoCapacidade1;
    private javax.swing.JTextField campoCapacidade2;
    private javax.swing.JTextField campoCapacitancia;
    private javax.swing.JTextField campoDescricao1;
    private javax.swing.JTextField campoDescricao2;
    private javax.swing.JTextField campoDescricaoCapacitor;
    private javax.swing.JTextField campoId1;
    private javax.swing.JTextField campoId2;
    private javax.swing.JTextField campoIdCapacitor;
    private javax.swing.JTextField campoQuantidade1;
    private javax.swing.JTextField campoQuantidade2;
    private javax.swing.JTextField campoQuantidadeCapacitor;
    private javax.swing.JComboBox<String> comboTipoCapacitancia1;
    private javax.swing.JComboBox<String> comboTipoCapacitancia2;
    private javax.swing.JComboBox<String> comboTipoCapacitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel tabCapacitores;
    private javax.swing.JPanel tabIndutores;
    private javax.swing.JPanel tabResistores;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbl_dep_dpts;
    private javax.swing.JTable tbl_dep_dpts1;
    private javax.swing.JTable tbl_dep_dpts2;
    // End of variables declaration//GEN-END:variables
}



